---
# This workflow will build a Java project with Maven
name: build

on:
  push:
    branches: [main, "[0-9]+.[0-9]+-SNAPSHOT"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/vpro/maven:18
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.12.1
        continue-on-error: true  # for act
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - name: Build and deploy with Maven
        run: |
          which yq
          ls /proc/docker
          mvn -B test deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v4
        with:
          files: report-aggregation/target/site/jacoco-aggregate/jacoco.xml
          verbose: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
